### ISSUE TITLE
The numbers in each column should be in ASCENDING ORDER

### ISSUE THREAD

**Issue by alphamike24** [ivebe/tombola#1]
![image](https://user-images.githubusercontent.com/19598096/80866281-6cbf6400-8cab-11ea-84c4-d1500e903ba8.png)

The numbers in every column should be in Ascending Order

**Comment by alphamike24** [comment]
Also, a Full Ticket consists of 6 Individual Tickets ( a user may choose between 1-6 tickets as per his / her own choice as every ticket has a incremental cost just like Lottery Tickets) but in all of them numbers are arranged as a unified ticket.

Please see the diagram of a ticket

![image](https://user-images.githubusercontent.com/19598096/80869224-e3189200-8cbc-11ea-96c7-8aac223153d4.png)

**Comment by alphamike24** [comment]
This is a Master Ticket containing 4 Individual Tickets
![image](https://user-images.githubusercontent.com/19598096/80869329-75209a80-8cbd-11ea-9e69-3c81f6241faf.png)

**Comment by alphamike24** [comment]
Precisely, we need an algorithm to create an array map for the number set generated for each column

Please see -
https://stackoverflow.com/questions/61481197/create-an-array-map-using-existing-array-of-numbers-while-meeting-conditions-rul

**Comment by ivebe** [comment]
I think you misunderstood something. Rules for the game are on the readme page, rule that columns must be in asc/desc order is simply not there, you can search online for some tombola tickets and see that they are random ordered. If you have some particular issue or found a bug feel free to report it, otherwise I don't understand what you expect here to be done.
